version: "1.0.0"
services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
    image: staffys_backoffice_client
    volumes:
      - .:/app
    container_name: staffys_backoffice_client_local
    ports:
      - 3001:3001
    tty: true
    entrypoint: ["npm", "run", "dev"]
