export const deliveryHistory = [
  {
    id: 1,
    address: "Calle 1",
    receptorName: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: true,
    status: "Entregado",
  },
  {
    id: 2,
    address: "Calle 2",
    receptorName: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: true,
    status: "Entregado",
  },
  {
    id: 3,
    address: "Calle 3",
    receptorName: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: true,
    status: "Entregado",
  },
  {
    id: 4,
    address: "Calle 4",
    receptorName: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: true,
    status: "Entregado",
  },
  {
    id: 5,
    address: "Calle 5",
    receptorName: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: true,
    status: "Entregado",
  },
  {
    id: 6,
    address: "Calle 6",
    receptorName: "Juan Perez",
    distance: "1.5 km",
    buttonText: "Tomar",
    trash: true,
    status: "Entregado",
  },
];
